### PR TITLE
Add support for Album name

### PR DESCRIPTION
**Pull request by ahayworth**
When `publish_parsed` is set, the `album` topic should be published which we can report to Home Assistant.

### CODE REVIEW

**Comment by parautenbach** [comment]
Thanks for the contribution!

Which version of Shairport Sync did you test it with?

Can't remember now whether I've seen the album topic before or whether it's in a new version.

**Comment by ahayworth** [comment]
Ah - I'm running the latest development `shairport-sync` (or at least, "latest" as of a week or so ago). The HA version tested against was `2022.4.5`.

Perhaps this is not a good idea to merge then, if it's not available in the current release of `shairport-sync`.

**Comment by parautenbach** [comment]
I'm happy to add it, no problem. :-) It also gives me a reason to upgrade SS. 

Could you maybe send me your exact configuration for SS? There should be a line like this in your logs:

```
Apr 19 17:24:55 rasplay shairport-sync:          0.005120769 "shairport.c:1730" software version: "3.3.7rc1-alac-OpenSSL-Avahi-ALSA-stdout-pipe-soxr-metadata-mq
tt-sysconfdir:/etc"
```

**Comment by ahayworth** [comment]
Definitely:

```
Apr 20 16:38:57 airplay2-kitchen shairport-sync[6195]:          0.000215407 "shairport.c:1924" Started in Airplay 2 mode with features 0x405fca00,0x1c
340 on device "a6:81:9a:88:0d:50"!
Apr 20 16:38:57 airplay2-kitchen shairport-sync[6195]:          0.000476213 "shairport.c:1967" software version: "4.1-dev-248-gbc97f76a-AirPlay2-alac-
OpenSSL-Avahi-pa-soxr-convolution-metadata-mqtt-sysconfdir:/etc"
```

**Comment by ahayworth** [comment]
It looks like it's been there from the very beginning, actually: https://github.com/mikebrady/shairport-sync/pull/716/files?show-viewed-files=true&file-filters%5B%5D=#diff-6c44d786e669b83985a5341ab82b29ddbd7567d377e12cb3e93f86207838d1f5R138

**Pull request merged**
